### ISSUE TITLE
KG-OBO Jenkins build fails due to missing ensmallen requirements

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-obo#127]
As detailed on the [GraPE README](https://github.com/AnacletoLAB/grape), ensmallen requires a certain set of CPU features to be available. Our build server does not have all of these features, so the build fails with a friendly ValueError.

**Solution**: Do a manual ensmallen build and prepare it as a wheel or other prebuilt binary, then install at build time.

**Comment by caufieldjh** [comment]
Will need to modify Jenkinsfile with ` . venv/bin/activate && pip install $LOCATION_OF_WHEEL`

**Comment by caufieldjh** [comment]
Building ensmallen on the build server fails:
```
...

error: failed to run custom build command for `cumsum_f32 v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#c36624e1)`

Caused by:
  process didn't exit successfully: `/home/harry/ensmallen/bindings/python/target/release/build/cumsum_f32-f66f74caa2d87e5b/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src/ccumsum.c
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-march=native" "-O3" "-o" "/home/harry/ensmallen/bindings/python/target/release/build/cumsum_f32-0e2e9a52222b81fa/out/src/ccumsum.o" "-c" "src/ccumsum.c"
  cargo:warning=src/ccumsum.c: In function ‘scan_AVX’:
  cargo:warning=src/ccumsum.c:125:1: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
  cargo:warning= inline __m256 scan_AVX(__m256 x) {
  cargo:warning= ^~~~~~
  cargo:warning=src/ccumsum.c:125:15: note: The ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
  cargo:warning= inline __m256 scan_AVX(__m256 x) {
  cargo:warning=               ^~~~~~~~
...
```

**Comment by zommiommy** [comment]
Hi Harry, I think that I forgot to add some conditional compilation attributes, sorry about that, I'm gonna fix it asap. Which branch are you using?

**Comment by caufieldjh** [comment]
Thanks @zommiommy - this is with the main branch.

**Comment by zommiommy** [comment]
Hi Harry, I pushed a new AVX-less implementation, now it should work.

If this is not enought you can try to modify the file `./graph/build.rs` from:
```rust
        cc::Build::new()
            .file("src/core.c")
            .flag("-march=native")
            .flag("-mtune=native")
            .flag("-msse4.1")
            .flag("-mavx")
            .flag("-mavx2")
            .flag("-mlzcnt")
            .flag("-O3")
            .compile("core.a");
```
to 
```rust
        cc::Build::new()
            .file("src/core.c")
            .flag("-march=native")
            .flag("-mtune=native")
            .flag("-O3")
            .compile("core.a");
```

If this is needed let me know and I will also add it to the repo.

Sorry for the bug!

**Comment by zommiommy** [comment]
I just realized that we will have the same problem on vec-rand, working on it.

**Comment by zommiommy** [comment]
Ok, not it should work (hopefully)

**Comment by caufieldjh** [comment]
Fantastic - thanks again! Will try a build again today and will let you know how it goes.

**Comment by caufieldjh** [comment]
Hrmm, looks like it still doesn't build, even after modifying `./graph/build.rs` as described:
```
...

error: failed to run custom build command for `cumsum_f32 v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#c36624e1)`

Caused by:
  process didn't exit successfully: `/home/harry/ensmallen/bindings/python/target/release/build/cumsum_f32-f66f74caa2d87e5b/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src/ccumsum.c
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-march=native" "-O3" "-o" "/home/harry/ensmallen/bindings/python/target/release/build/cumsum_f32-0e2e9a52222b81fa/out/src/ccumsum.o" "-c" "src/ccumsum.c"
  cargo:warning=src/ccumsum.c: In function ‘scan_AVX’:
  cargo:warning=src/ccumsum.c:125:1: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
  cargo:warning= inline __m256 scan_AVX(__m256 x) {
  cargo:warning= ^~~~~~

...

  --- stderr


  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-march=native" "-O3" "-o" "/home/harry/ensmallen/bindings/python/target/release/build/cumsum_f32-0e2e9a52222b81fa/out/src/ccumsum.o" "-c" "src/ccumsum.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib --`
```

Looks like the build breaks at `vec_rand`?

**Comment by zommiommy** [comment]
Ok, sorry. I'm working on it!

**Comment by zommiommy** [comment]
Ok, run `cargo update` in the `graph` folder, and try again

**Comment by caufieldjh** [comment]
Got it to build an `ensmallen` wheel now - thanks again, @zommiommy!

**Comment by zommiommy** [comment]
no problem! sorry again for the bug!

**Comment by caufieldjh** [comment]
Looks like there's one remaining piece, @zommiommy - importing the compiled ensmallen bindings throws a ValueError because the required flags still aren't found: https://github.com/AnacletoLAB/ensmallen/blob/master/bindings/python/ensmallen/__init__.py
For KG-OBO purposes I'll just comment out the error, but this will cause any further AVX-less implementations to fail upon import.

**Comment by zommiommy** [comment]
You are absolutely right, we added that check for the precompiled version, but will make any version compiled with different flags or cpu arch.

I'm gonna try to find a way to fingerprint fhe compilation flags so that they can be properly checked

**Comment by zommiommy** [comment]
Hopefully done! I've added a `build.rs` script that automatically dump the compilation informations in a python file so that we can check it before importing the compiled library.

The generated file running `maturin develop --strip --release` looks like this:
```python

# Library Compilation flags
FLAGS = ["fxsr", "sse", "sse2"]
TARGET_TRIPLE = "x86_64-unknown-linux-gnu"
CPU_ARCH = "x86_64"
OS = "linux"
ENDIANESS = "little"

# Compilation host info
HOST = "x86_64-unknown-linux-gnu"
OPT_LEVEL = "3"
TOOLCHAIN = "nightly-2021-09-01-x86_64-unknown-linux-gnu"
```
While running `RUSTFLAGS="-C target-cpu=native" maturin develop --strip --release` on my AMD 3900x it results in:
```python
# Library Compilation flags
FLAGS = ["adx", "aes", "avx", "avx2", "bmi1", "bmi2", "cmpxchg16b", "f16c", "fma", "fxsr", "lzcnt", "movbe", "pclmulqdq", "popcnt", "rdrand", "rdseed", "sha", "sse", "sse2", "sse3", "sse4.1", "sse4.2", "sse4a", "ssse3", "xsave", "xsavec", "xsaveopt", "xsaves"]
TARGET_TRIPLE = "x86_64-unknown-linux-gnu"
CPU_ARCH = "x86_64"
OS = "linux"
ENDIANESS = "little"

# Compilation host info
HOST = "x86_64-unknown-linux-gnu"
OPT_LEVEL = "3"
TOOLCHAIN = "nightly-2021-09-01-x86_64-unknown-linux-gnu"
\
```

And the check now is:
```python

import os
from .compilation_flags import FLAGS, TARGET_TRIPLE, OS, CPU_ARCH

# Check that the OS and the CPU Arch match, this should be already done by pip
# but better check twice 
if os.uname().sysname.lower().strip() != OS.lower().strip() \
    or os.uname().machine.lower().strip() != CPU_ARCH.lower().strip():
    raise ValueError((
        "This version of the library was compiled for '{}' assuming the ",
        "following flags '{}'. You souldn't have been able to install this as ",
        "pip should have already catched this error. ",
        "Please open an Issue on Github detailing the installation process ",
        "you used so we can debug it."
        ).format(TARGET_TRIPLE, FLAGS)
    )

import cpuinfo

unavailable_flags = set(FLAGS) - set(cpuinfo.get_cpu_info()["flags"])

if len(unavailable_flags) > 0:
    raise ValueError(
        (
            "On the current machine, the flags '{}' are not available.\n"
            "This library was compiled assuming that the following instruction ",
            "sets are available: {}\n",
            "You can solve this issue by manually compiling ensmallen tailoring",
            " it to your hardware following the guides on our Github repository."
            " Ensmallen has no strict dependancy on any flag or cpu_arch as it ",
            "can be compiled for any arch supported by LLVM (Arm, AArch64, Mips,",
            " ...). Supporting"
            "\nIn particular, the pip pre-compiled versions are aimed to x86_64",
            "Cpus with architecture newer or equal to Haswell (2013).",
            "This is done because we heavily explioit both SSE and AVX ",
            "instructions which allows great speed-ups of several core routines",
            "and providing pre-compiled versions for all cpu arches with ",
            "all flags combinations for all operating systems would have a ",
            "prohibitive cost."
        ).format(unavailable_flags, FLAGS)
    )
```

I hope this should allow us to have always updated info about the compialtion info and help the user (btw if you have any suggestions or ideas to improve the error messages please share them!)

**Comment by zommiommy** [comment]
I had to update the vec_rand crate again, hope that everything still works

**Comment by caufieldjh** [comment]
Fantastic - looks like a thorough solution to me. Thanks for all your work!

**Comment by zommiommy** [comment]
btw there was a little python error in the `__init__.py` file, I just pushed a fix so if it doesn't work just run `git pull`

**Comment by caufieldjh** [comment]
Aha, I just ran into that error. Glad you noticed it already.

**Comment by caufieldjh** [comment]
I believe this is no longer an issue - thanks again @zommiommy
